# This is a basic workflow to help you get started with Actions

name: Windows CI

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Submoudle
    - name: Checkout Submodles
      run: git submodule update --init --recursive
    # Setup MSBuild For Later Usage
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '16.6.2'
    # Run MSBuild
    - name: Build Solution
      run: msbuild "D:\a\Project64-Netplay\Project64-Netplay\Project64 Netplay.sln" /verbosity:minimal /property:Configuration=Release  /property:Platform=Win32
    # Run Package
    - name: Package
      run:  "cd D:\a\Project64-Netplay\Project64-Netplay\"= && package.cmd"

    # Upload Artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PJ64Netplay-dev
        path: D:\a\Project64-Netplay\Project64-Netplay\Package\
